spring:
  jpa:
    enabled: true
  datasource:
    shard1:
      url: jdbc:oracle:thin:@db-shard-1:1521:orcl
      username: shard1_user
      password: shard1_pass
      driver-class-name: oracle.jdbc.OracleDriver
    shard2:
      url: jdbc:oracle:thin:@db-shard-2:1521:orcl
      username: shard2_user
      password: shard2_pass
      driver-class-name: oracle.jdbc.OracleDriver
